exports.facRecordModel = {
    "idDHIS2": "",
    "fosaCode" : "",
    "name" : "",
    "description" : "",
    "url" : "",
    "type" : "",  
    "province" : "",
    "district" : "",
    "subdistrict" : "",
    "sector" : "",
    "umudugudu" : "",
    "openingDate" : "",
    "closingDate" : "",
    "email" : "",
    "phoneNumber" : "",
    "manager" : "",
    "coordinates" : "",
    "extractDate" : ""
}